---
name: "Template"
guid: "6bfde2dd-8211-4964-b86d-7812a9de160b"
version: "1.0.0.0"
targetAbi: "10.10.0.0"
framework: "net8.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "jellyfin"
artifacts:
- "KappuCitti.Plugin.SyncVote.dll"
changelog: >
  changelog
